### ISSUE TITLE
Error with activating virtual environment

### ISSUE THREAD

**Issue by zswalker** [CSC-256-Group-Project-9/Group-9-Selenium-Lab#13]
I ran into an issue activating the virtual environment for Selenium Lab. 
I followed all the steps in setup environment prior to the activate command. I cloned the repository, checked out basic-scripting, and ran the command to create the virtual environment.

This is the error I received.
![image](https://github.com/CSC-256-Group-Project-9/Group-9-Selenium-Lab/assets/103614234/7d99aebd-18af-4dbc-8559-1c0d098e295b)

**Comment by Robomonster** [comment]
Updated README.md with new instructions in [7557b89](https://github.com/CSC-256-Group-Project-9/Group-9-Selenium-Lab/commit/7557b898157320138118f9991bf8c46c5942cd9b)
