### ISSUE TITLE
Group_9_Selenium_Lab.docx - Setup Environment step

### ISSUE THREAD

**Issue by zswalker** [CSC-256-Group-Project-9/Group-9-Selenium-Lab#15]
Document: Group_9_Selenium_Lab.docx
Location: https://github.com/CSC-256-Group-Project-9/Group-9-Selenium-Lab/tree/main/For-Students

Issue: git checkout command
Description: In the Setup Environment, since the project was merged into the main branch, basic-scripting branch is no longer available.

![image](https://github.com/CSC-256-Group-Project-9/Group-9-Selenium-Lab/assets/103614234/64aacb5b-23dc-4b95-a944-6ed8ee400be4)

**Comment by doombot696** [comment]
Resolved!
