### ISSUE TITLE
Stuck on Step 2. Install requirements.txt

### ISSUE THREAD

**Issue by doombot696** [CSC-256-Group-Project-9/Group-9-Selenium-Lab#8]
Steps to Reproduce:

1. Follow steps 0: Setup Virtual Environment
2. Follow steps 1: Activate Virtual Environment
3. Step 2: In the virtual environment in the powershell command prompt, type:

pip install -r requirements.txt

Output/Error:

![Image](https://github.com/CSC-256-Group-Project-9/Group-9-Selenium-Lab/assets/28795098/60d65ae8-4692-47a1-9fcc-40e7e28c1672)

Expected Output/Result:

All of the requirements should have been installed for the selenium lab.

**Comment by HaffCaff** [comment]
@doombot696 Before you run that script, after switching to the scripting branch, did you do a `git pull`?

**Comment by doombot696** [comment]
> @doombot696 Before you run that script, after switching to the scripting branch, did you do a `git pull`?

Yes I have. The requirements.txt is also located within the path I am trying to install it, so there should be no issues

![image](https://github.com/CSC-256-Group-Project-9/Group-9-Selenium-Lab/assets/28795098/2a08512b-95b2-4ca0-814e-a8404edfc6b0)

**Comment by Robomonster** [comment]
@doombot696 Can you run the following commands from a powershell window in the repository directory and show the output of each.

    Get-Content .\requirements.txt

**From within the virtual environment** after activating it using <code>.\venv\Scripts\Activate.ps1</code>

    python --version

and

    python -m site

**Comment by doombot696** [comment]
Here you go, I have attached the output of all those lines you requested that I type in

![image](https://github.com/CSC-256-Group-Project-9/Group-9-Selenium-Lab/assets/28795098/27bc4c3d-eb6f-40c8-89b4-28cb180525ca)

**Comment by doombot696** [comment]
Closed Issue #8, issue was local-sided. Typing in "python -m pip install -r requirements.txt" for Step 2 instead of "pip install -r requirements.txt" fixes the issue and makes the program run as usual.
